### ISSUE TITLE
Compilation with Nanos6 for OmpSs-2

### ISSUE THREAD

**Issue by Z10Frank** [bsc-pm/mcxx#38]
Dear developers,
I wanted to try a simple preliminary test with https://pm.bsc.es/gitlab/ompss-2/examples/dot-product, so I am trying to compile Nano6 and Mercurium to have the `mcc` file for `OmpSs-2`. 

Following the instructions online (https://pm.bsc.es/ftp/ompss-2/doc/user-guide/OmpSs-2-User-Guide.pdf), I have successfully compiled Nanos6 (cloned from https://github.com/bsc-pm/nanos6) with this compilation script [compile_Nanos6.txt](https://github.com/bsc-pm/mcxx/files/7827718/compile_Nanos6.txt) . Afterwards, while compiling Mercurium (cloned from https://github.com/bsc-pm/mcxx), I obtain an error:
```
+ make -j 20
make: *** No rule to make target `src/frontend/cxx-asttype.def', needed by `src/frontend/cxx-asttype.c'.  Stop.
+ make install
make: *** No rule to make target `src/frontend/cxx-asttype.def', needed by `src/frontend/cxx-asttype.c'.  Stop.
```
Attached is the compilation file for Mercurium  
[compile_Mercurium.txt](https://github.com/bsc-pm/mcxx/files/7827715/compile_Mercurium.txt)
and the log file from its compilation ,
[compilation_Mercurium_log.txt](https://github.com/bsc-pm/mcxx/files/7827717/compilation_Mercurium_log.txt)
 Please do not hesitate to ask me more info or logs to help solving the problem.

Also, the same error occurs if I try to compile without the flag `--with-nanos6=...` .
When I try to compile Mercurium and Nanosx from tarball on the same machine for `OmpSs` all seems to work and the `mcc` file is created.

What do you think it could be the cause of the error?

Thanks in advance for your time.

**Comment by rofirrim** [comment]
Hi @Z10Frank,

this is a bug caused by the absence of some tools at compile time. While we attempt to support this case, `make` my led to believe it needs to regenerate some files (I've looked into this issue a few times before, I seem to recall it looked like one file was regenerated using a script which requires no extra dependences but then this file is an input of one of those files that requires extra tools).

The tools I mean are those reported at the end of the configure:

```
configure: WARNING: flex files (*.l) will not be considered for regeneration
configure: WARNING: bison files (*.y) will not be considered for regeneration
configure: WARNING: gperf files (*.gperf) will not be considered for regeneration
```

Would it be possible for you to make sure `flex`, `bison` and `gperf` are available at configure time and try again? This is not a full solution, more a workaround. Let me know if this solves this issue for you.

Thanks!

**Comment by Z10Frank** [comment]
Thank you!
I have installed the libraries (`bison-2.6.5`, `flex-2.6.4`, `gperf-3.1`) on the cluster where I am working on. Since I have not the authorisations to install in the usual shared paths, they are installed in custom paths like `$HOME/bison-2.6.5/install`.

The Mercurium compilation probably looks for them in the default shared paths, and I can't find dedicated flags for the `./configure` file.

Commands like `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/bison-2.6.5/install/` etc. do not seem to solve the issue, is there a way to make these dependencies visible to the `configure`?

**Comment by rofirrim** [comment]
Hi @Z10Frank,

You will have to set the environment variables `BISON`, `FLEX` `GPERF` at the configure line (make them be the path to the corresponding tool).

There is a number of these kind of variables that you can list using `configure --help`

```bash 
$ ./configure BISON=/path/to/bison FLEX=/path/to/flex GPERF=/path/to/gperf <rest of the configure flags>
```

Let me know if this helps.

Kind regards

**Comment by Z10Frank** [comment]
Thank you! I have used 
```
export MERCURIUM=/gpfs/users/massimof/ompss-19.06/mcxx-2.3.0/install
export BISON=/gpfs/users/massimof/bison-2.6.5/install
export FLEX=/gpfs/users/massimof/flex-2.6.4/install
export GPERF=/gpfs/users/massimof/gperf-3.1/install
export NANOSSIX=/gpfs/users/massimof/nanos6/install
export GIT=/gpfs/softs/spack/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/git-2.25.0-lojbmyepxnaay2yotcnyzwwty36rnjyq

./configure BISON=$BISON FLEX=$FLEX GPERF=$GPERF GIT=$GIT --prefix=$MERCURIUM --enable-ompss-2 --with-nanos6=$NANOSSIX

make -j 10

make install
```
Now the log file shows that the requirements are recognised:
```
* Tools configured:

   Flex : /gpfs/users/massimof/flex-2.6.4/install
   GNU bison : /gpfs/users/massimof/bison-2.6.5/install
   GNU gperf : /gpfs/users/massimof/gperf-3.1/install
   git content tracker: /gpfs/softs/spack/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/git-2.25.0-lojbmyepxnaay2yotcnyzwwty36rnjyq
   SQLite 3 cflags: -I/gpfs/softs/spack/opt/spack/linux-centos7-cascadelake/intel-19.0.3.199/sqlite-3.30.1-saq7stuwy6563nyakbi42nkwjpapha6g/include
   SQLite 3 libs: -L/gpfs/softs/spack/opt/spack/linux-centos7-cascadelake/intel-19.0.3.199/sqlite-3.30.1-saq7stuwy6563nyakbi42nkwjpapha6g/lib -lsqlite3
``` 
I guess this will surely help, but the same error persists:
[compilation_Mercurium_new.txt](https://github.com/bsc-pm/mcxx/files/7844654/compilation_Mercurium_new.txt)

**Comment by rofirrim** [comment]
Hi @Z10Frank ,

try `make clean` and then `make- j$(nproc)` and let me know.

Kind regards,

**Comment by Z10Frank** [comment]
Thank you, but the main difference after a `make clean` and `make` seems the message `CCBUILD  lib/perish.o` at the end:
[compilation_Mercurium_new2.txt](https://github.com/bsc-pm/mcxx/files/7844711/compilation_Mercurium_new2.txt)

**Comment by rofirrim** [comment]
Hi @Z10Frank,

Ok I didn't spot earlier what was going on

```
checking for nvcc... no
checking for flex... /gpfs/users/massimof/flex-2.6.4/install
checking flex version... ./configure: line 25797: /gpfs/users/massimof/flex-2.6.4/install: Is a directory
error, could not guess flex version
checking for bison... /gpfs/users/massimof/bison-2.6.5/install
checking bison version... ./configure: line 25915: /gpfs/users/massimof/bison-2.6.5/install: Is a directory
error, could not guess bison version
checking for gperf... /gpfs/users/massimof/gperf-3.1/install
checking gperf version... ./configure: line 26015: /gpfs/users/massimof/gperf-3.1/install: Is a directory
error, could not guess gperf version```

Don't specify the directory, do specify the binary itself as in `/gpfs/users/massimof/gperf-3.1/install/bin/gperf`

**Comment by Z10Frank** [comment]
It worked, thank you so much for all the help!
With 
```
OMPSSTWO=/gpfs/users/massimof/mcxx/install/bin
export PATH=$OMPSSTWO:$PATH
make 
make run
```
I was able to compile the example in https://pm.bsc.es/gitlab/ompss-2/examples/dot-product, the results seems ok:
```
./01.dot_product_seq $((1024*256)) 8192
size (K), 262144, chunk (K), 8192, time (ms), 2118
./02.dot_product_task+dep $((1024*256)) 8192
size (K), 262144, chunk (K), 8192, time (ms), 617
./03.dot_product_task+reduction $((1024*256)) 8192
size (K), 262144, chunk (K), 8192, time (ms), 209
```
